apiVersion: v1
kind: Service
metadata:
  name: yuripereira-model-predictor-service
  namespace: yuripereira
spec:
  selector:
    app: yuripereira-model-predictor
  ports:
    - protocol: TCP
      port: 52064
      targetPort: 52064