apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuripereira-model-predictor-deployment
  namespace: yuripereira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yuripereira-model-predictor
  template:
    metadata:
      labels:
        app: yuripereira-model-predictor
      annotations:
        configmap-hash: "{{ .ConfigMap | sha256sum }}"
    spec:
      containers:
      - name: yuripereira-model-predictor
        image: quay.io/yurilpbh/tp2:v0.0.20
        ports:
        - containerPort: 52064
        volumeMounts:
        - name: yuripereira-model-predictor-deployment
          mountPath: "/dataset"
        - name: yuripereira-spotify-dataset
          mountPath: "/dataset"
          subPath: spotify_ds.csv
      volumes:
      - name: yuripereira-model-predictor-deployment
        persistentVolumeClaim:
          claimName: project2-pv2-yuripereira
      - name: yuripereira-spotify-dataset
        configMap:
          name: spotify-configmap