apiVersion: batch/v1
kind: Job
metadata:
  name: yuripereira-model-predictor-job_1
  namespace: yuripereira
spec:
  revisionHistoryLimit: 1
  template:
    spec:
      containers:
      - name: yuripereira-model-predictor-job-container
        image: quay.io/yurilpbh/tp2:v0.0.22
        volumeMounts:
        - name: yuripereira-model-predictor-job_1
          mountPath: "/dataset"
      volumes:
      - name: yuripereira-model-predictor-job_1
        persistentVolumeClaim:
          claimName: project2-pv2-yuripereira
      restartPolicy: Never
  backoffLimit: 1