apiVersion: batch/v1
kind: Job
metadata:
  name: yuripereira-model-predictor-job
  namespace: yuripereira
spec:
  template:
    metadata:
      annotations:
        checksum/configmap: "{{ .Values.csv-configmap.data.csv_hash }}" # Track the hash
    spec:
      containers:
      - name: yuripereira-model-predictor-job-container
        image: quay.io/yurilpbh/tp2:v0.0.22
        volumeMounts:
        - name: yuripereira-model-predictor-job
          mountPath: "/dataset"
      volumes:
      - name: yuripereira-model-predictor-job
        persistentVolumeClaim:
          claimName: project2-pv2-yuripereira
      restartPolicy: Never
  backoffLimit: 1