apiVersion: batch/v1
kind: Job
metadata:
  name: yuripereira-model-predictor-job-42178827e7
  namespace: yuripereira
spec:
  template:
    spec:
      containers:
      - name: yuripereira-model-predictor-job-container
        image: quay.io/yurilpbh/tp2:v0.0.23
        volumeMounts:
        - name: yuripereira-model-predictor-job-42178827e7
          mountPath: "/dataset"
      volumes:
      - name: yuripereira-model-predictor-job-42178827e7
        persistentVolumeClaim:
          claimName: project2-pv2-yuripereira
      restartPolicy: Never
  backoffLimit: 1
