apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuripereira-predictor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yuripereira-predictor
  volumes:
    - name: yuripereira-predictor-deployment
      persistentVolumeClaim:
        claimName: project2-pv2-yuripereira
  template:
    metadata:
      labels:
        app: yuripereira-predictor
    spec:
      containers:
      - name: yuripereira-predictor
        image: yurilp/tp2_3:playlist-recommender_0.2
        ports:
        - containerPort: 52064
        volumeMounts:
        - name: yuripereira-predictor-deployment
          mountPath: "/home/yuripereira/project2-pv2"