apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuripereira-predictor-deployment
  namespace: yuripereira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yuripereira-predictor
  template:
    metadata:
      labels:
        app: yuripereira-predictor
    spec:
      containers:
      - name: yuripereira-predictor
        image: yurilp/tp2_3:playlist-recommender_0.0.1
        ports:
        - containerPort: 52064
        volumeMounts:
        - name: yuripereira-predictor-deployment
          mountPath: "/home/yuripereira/project2-pv2"
      volumes:
      - name: yuripereira-predictor-deployment
        persistentVolumeClaim:
          claimName: project2-pv2-yuripereira