apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuripereira-predictor-deployment
  namespace: yuripereira
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: yuripereira-predictor
  template:
    metadata:
      labels:
        app: yuripereira-predictor
    spec:
      containers:
      - name: yuripereira-predictor
        image: quay.io/yurilpbh/tp2_server:v0.0.10
        ports:
        - containerPort: 52064
        volumeMounts:
        - name: yuripereira-predictor-deployment
          mountPath: "/dataset"
      volumes:
      - name: yuripereira-predictor-deployment
        persistentVolumeClaim:
          claimName: project2-pv2-yuripereira