apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-pv2-yuripereira
  namespace: yuripereira
spec:
  storageClassName: default-storage-class-yuripereira
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi