apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yuripereira-predictor-pvc
  namespace: yuripereira
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: default-storage-class-yuripereira