apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-yuripereira
spec:
  storageClassName: default-storage-class-yuripereira
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: yuripereira