name: Update ConfigMap with sha256 of CSV

on:
  push:
    paths:
      - "dataset/spotify_ds.csv"
      - "kubernets/backend-configmap.yaml"

jobs:
  update-configmap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up kubectl and Helm
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    # Step 3: Authenticate with Kubernetes
    - name: Authenticate with Kubernetes
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "${KUBE_CONFIG_DATA}" | base64 --decode > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    # Step 4: Fetch the latest checksum from the ConfigMap
    - name: Get ConfigMap checksum
      id: get-checksum
      run: |
        CHECKSUM=$(kubectl get configmap spotify-configmap -n yuripereira -o jsonpath="{.data.spotify_sha256}")
        echo "checksum=$CHECKSUM" >> $GITHUB_ENV

    # Step 5: Redeploy the Job with the updated checksum
    - name: Deploy Updated Job
      run: |
        helm upgrade --install my-release my-chart \
          --set checksum.configmap=$checksum
      
