name: Update ConfigMap with CSV

on:
  push:
    # paths:
    #   - "dataset/spotify_ds.csv"

jobs:
  update-configmap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Kubernetes Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Authenticate to Kubernetes
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "${KUBE_CONFIG_DATA}" > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Update ConfigMap YAML
      run: |
        # Read the CSV content and encode it for the ConfigMap
        csv_data=$(cat dataset/spotify_ds.csv | sed 's/^/    /')

        # Update the ConfigMap YAML file
        cat <<EOF > kubernets/backend-configmap.yaml
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: spotify-configmap
          namespace: yuripereira
        data:
          spotify.csv: |
            $csv_data
        EOF
      
    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add kubernets/backend-configmap.yaml
        git commit -m "Update ConfigMap with latest spotify_ds.csv"
        git push
      
