name: Update ConfigMap with sha256 of CSV

on:
  push:
    paths:
      - "dataset/spotify_ds.csv"

jobs:
  update-configmap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update ConfigMap YAML
      run: |
        # Read the CSV content and encode it for the ConfigMap
        csv_hash=$(sha256sum dataset/spotify_ds.csv | awk '{print $1}')

        # Update the ConfigMap YAML file
        cat <<EOF > kubernets/values.yaml
        checksum:
          configmap: $csv_hash
        EOF
      
    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add kubernets/backend-configmap.yaml
        git commit -m "Update ConfigMap with sha256 of spotify_ds.csv"
        git push
      
