name: Update ConfigMap with CSV

on:
  push:
    # paths:
    #   - "dataset/spotify_ds.csv"

jobs:
  update-configmap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Kubernetes Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Authenticate to Kubernetes
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "${KUBE_CONFIG_DATA}" > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Update ConfigMap
      run: |
        cd kubernets
        kubectl create configmap spotify-dataset \
          --namespace yuripereira \
          --from-file="../dataset/spotify_ds.csv" \
          --dry-run=client --validate=false -o yaml | kubectl apply -f -
